# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XHMoyaNetworkTool' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod ‘Moya’
pod ‘Moya/RxSwift’
pod ‘SwiftyJSON’
pod ‘RxSwift’
pod ‘RealmSwift’
pod ‘RxCocoa’

  # Pods for XHMoyaNetworkTool

end
